[build]
  publish = "."
  command = "echo 'Building Corner Deli Site'"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
